### TDMPC2 config ###
# environment
task: ACBohnNoVaIErr
obs: state

# training
steps: 750_000

periodic_eval: true
eval_freq: 37_500 # This will make 20 evaluations points
eval_episodes: ??? # this value is overwritten by the size of the reference sequence in the code
final_traj_plot: true # simulate a final trajectory at the end of training (for visualization + log in wandb)

# logging
wandb_project: tdmpc2
wandb_entity: thesedavid
wandb_silent: false
disable_wandb: false

# misc
save_agent: true
seed: ???
render_mode: 'none'

# CAPS
use_caps: false
ts_coef: 0.0

# use mppi type planning or pi policy direct output
mpc: true
